name: 'Replace multiple strings in files'
description: 'Find and replace multiple strings over matching files'
author: 'David Gardiner'
branding:
  icon: search
  color: blue
inputs:
  files:
    required: true
    description: 'Globbing pattern to match files to search'
    default: '**/*.md'
  find:
    required: true
    description: 'JSON array of strings to find and replacements'
  encoding:
    required: false
    description: 'Encoding of files to search. Should be one of ascii, utf8, utf-8, utf16le, ucs2, ucs-2'
    default: 'utf-8'

runs:
  using: 'node16'
  main: 'dist/index.js'

