name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    outputs:
      NBGV_SemVer2: ${{ steps.gitversion.outputs.NBGV_SemVer2 }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full history for GitVersioning
      - run: |
          npm ci
          npx nbgv cloud --all-vars

      - name: gitversion
        id: gitversion
        run: |
          echo "set-output name=NBGV_SemVer2::$NBGV_SemVer2"
          echo "::set-output name=NBGV_SemVer2::$NBGV_SemVer2"

      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Node.js 20.x
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20.x
      - uses: ./
        with:
          files: './*.md'
          find: '[{ "find": "Multiple", "replace": "Many" }]'

      - uses: ./
        with:
          files: './*.md'
          find: '[{ "find": "Multiple", "replace": "Many" }]'
          prefix: ''
          suffix: ''

      - uses: ./
        with:
          files: '__tests__/nodejs-*/.envfile'
          find: '[{ "find": "DB_HOST=", "replace": "DB_HOST=dbserver" }]'
          prefix: ''
          suffix: ''
  

  update_release_draft:
    name: Update release draft
    runs-on: ubuntu-latest
    needs: [build]
    env:
      NBGV_SemVer2: ${{ needs.build.outputs.NBGV_SemVer2 }}

    if: github.ref == 'refs/heads/main' # Running this job only for master branch
    steps:
      - uses: actions/checkout@v4

      - uses: release-drafter/release-drafter@v6
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: ${{ needs.build.outputs.NBGV_SemVer2 }}
